// English UI strings. Keys are dot-namespaced by area.
export default {
  // ── Common ──
  "common.cancel": "Cancel",
  "common.close": "Close",
  "common.closeNamed": "Close {name}",
  "common.create": "Create",
  "common.add": "Add",
  "common.done": "Done",
  "common.retry": "Retry",
  "common.save": "Save",
  "common.saved": "Saved",
  "common.search": "Search...",
  "common.settings": "Settings",
  "common.version": "Version",
  "common.back": "Back",
  "common.copied": "Copied",
  "common.copyFailed": "Copy failed",
  "common.productName": "pican",

  // ── Runtimes ──
  "runtime.pi": "Pi",
  "runtime.codex": "Codex",
  "runtime.claude": "Claude",
  "runtime.opencode": "OpenCode",

  // ── Sessions index ──
  "index.title": "pican",
  "index.searchSessions": "Search sessions...",
  "index.sessionsCount": "{count} sessions",
  "index.sessionCountOne": "1 session",
  "index.activeCount": "({count} active)",
  "index.active": "active",
  "index.allIdle": "all idle",
  "index.runningCount": "{count} running",
  "index.needsYouCount": "{count} needs you",
  "index.projects": "Projects",
  "index.idle": "idle",
  "index.runningStatus": "{activity} · {elapsed}",
  "index.waitingStatus": "waiting {elapsed} — {question}",
  "index.working": "working",
  "index.durationSeconds": "{count}s",
  "index.durationMinutes": "{count}m",
  "index.durationHours": "{count}h",
  "index.durationDays": "{count}d",
  "index.newSessionShort": "New session",
  "index.openMenu": "Open menu",
  "index.mobileActions": "Session actions",
  "index.homeRail": "Waiting sessions",
  "index.waitingOnYou": "Waiting on you",
  "index.answerQuestion": "Answer {answer} for {question}",
  "index.openWaitingSession": "Open session to answer",
  "index.answerFailed": "Could not send answer",
  "index.layoutTimeline": "Timeline",
  "index.layoutProjects": "Projects",
  "index.sessionScope": "Session scope",
  "index.scopeProjects": "Projects",
  "index.scopeAll": "All Sessions",
  "index.scopeArchived": "Archived",
  "index.projectsShown": "{projects} projects · {shown} shown",
  "index.addProject": "Add project",
  "index.addRemoveProjects": "Add/remove projects",
  "index.backToProjects": "Back to projects",
  "index.dateToday": "Today",
  "index.dateYesterday": "Yesterday",
  "index.datePrevious7Days": "Previous 7 days",
  "index.datePrevious30Days": "Previous 30 days",
  "index.dateOlder": "Older",
  "index.loadMore": "Load more",
  "index.loadingMore": "Loading…",
  "index.newSession": "New Session",
  "index.manageProjects": "Manage Projects",
  "index.startNewSession": "Start a new session",
  "index.runtimeLabel": "Runtime",
  "index.runtimeUnavailable": "Unavailable",
  "index.runtimeUnavailableReason": "Unavailable — {reason}",
  "index.runtimeCreateUnsupported": "Doesn't support creating sessions",
  "index.claudePermissionsWarning":
    "Claude runs without permission prompts and can access your system.",
  "index.runtimeBadgeTitle": "Codex runtime",
  "index.sessionPathPlaceholder": "/path/to/project or ~/project",
  "index.pathWillBeCreated": "New folder — will be created on first run",
  "index.browseHint": "Directory suggestions",
  "index.dirHintNavigate": "Navigate",
  "index.dirHintEnterDir": "Enter dir",
  "index.dirHintCreate": "Create",
  "index.dirHintClose": "Close",
  "index.manageProjectsTitle": "Manage projects",
  "index.manageTrackedProjects": "Tracked projects",
  "index.trackedProjectsHint":
    "Choose the project folders shown on home. Other sessions stay available in All Sessions.",
  "index.addProjectPath": "Project path",
  "index.addTrackedProject": "Add",
  "index.removeTrackedProject": "Remove",
  "index.filterProjects": "Filter projects",
  "index.searchProjects": "Search projects…",
  "index.deselectAll": "Deselect all",
  "index.selectAll": "Select all",
  "index.registerFolder": "Register a folder",
  "index.loadingSessions": "Loading sessions…",
  "index.loadingSessionsHint": "Fetching the latest session list.",
  "index.noSessionsYet": "no sessions yet",
  "index.noSessionsYetHint": "press + to start one in {project}",
  "index.defaultProject": "home",
  "index.importSession": "Import session",
  "index.sessionLayout": "Session layout",
  "index.pinned": "Pinned",
  "index.noPinnedSessions": "No pinned sessions",
  "index.noPinnedSessionsHint": "Pin from a session’s more menu to keep it here.",
  "index.showAllPins": "All {count}",
  "index.showFewerPins": "Show fewer",
  "index.pinSession": "Pin session",
  "index.unpinSession": "Unpin session",
  "index.archiveSession": "Archive session",
  "index.restoreSession": "Restore session",
  "index.moreSessionActions": "More session actions",
  "index.archiveDisabledRunning": "Stop this session before archiving it.",
  "index.archiveDisabledWaiting": "Answer this session before archiving it.",
  "index.archiveUpdateFailed": "Couldn’t update this session’s archive state.",
  "index.closeNewSession": "Close Start a new session",
  "index.closeManageProjects": "Close Manage projects",
  "index.noProjectsMatch": "No projects match your search.",
  "index.noProjectsFound": "No projects found yet.",
  "index.noTrackedProjects": "No tracked projects",
  "index.noTrackedProjectsHint": "Add a project, or open",
  "index.openAllSessions": "All Sessions.",
  "index.noProjectSessions": "No sessions in this project",
  "index.noArchivedSessions": "No archived sessions",
  "index.noArchivedSessionsHint": "Archive an idle session to move it out of normal views.",
  "index.viewAllCount": "View all {count}",
  "index.viewOnly": "View only",
  "index.removeProject": "Remove",
  "index.enterPath": "Please enter a path",
  "index.failedCreateSession": "Failed to create session",
  "index.networkError": "Network error",
  "index.failedLoadProjects": "Failed to load projects",
  "index.failedUpdateProject": "Failed to update project",
  "index.filterOnDesc": "Only checked projects appear on the homepage.",
  "index.filterOffDesc": "All projects are shown. Turn on to show only the checked ones.",
  "index.machines": "Machines",
  "index.machinesOnlineCount": "{online}/{total} online",
  "index.machineOnline": "Online",
  "index.machineOffline": "Offline",
  "index.machineSessionCount": "{count} sessions",
  "index.machineSessionCountOne": "1 session",
  "index.machineNoSessions": "No sessions",
  "index.machineExpand": "Show sessions",
  "index.machineCollapse": "Hide sessions",
  "index.machineOpenOnHost": "Opens on {name} in a new tab",

  // ── Workflows ──
  "workflows.navTitle": "Workflows",
  "workflows.title": "Workflows",
  "workflows.sessionScope": "Workflows for this session",
  "workflows.loading": "Loading workflows…",
  "workflows.loadingRun": "Loading workflow…",
  "workflows.emptyTitle": "No workflow runs yet",
  "workflows.emptyHint": "Runs will appear here when the workflows extension creates them.",
  "workflows.backToList": "Back to workflows",
  "workflows.untitled": "Untitled workflow",
  "workflows.timeUnknown": "Start time unavailable",
  "workflows.phaseProgress": "{current}/{total} phases",
  "workflows.agentCount": "{count} agents",
  "workflows.started": "Started",
  "workflows.finished": "Finished",
  "workflows.sessionId": "Session ID",
  "workflows.phases": "Phases",
  "workflows.phaseFallback": "Phase {index}",
  "workflows.agents": "Agents",
  "workflows.agentFallback": "Agent {index}",
  "workflows.transcripts": "Transcripts",
  "workflows.noTranscripts": "No transcripts recorded.",
  "workflows.entryCount": "{count} entries",
  "workflows.result": "Result",
  "workflows.script": "Script",
  "workflows.error": "Error",
  "workflows.status.running": "Running",
  "workflows.status.completed": "Completed",
  "workflows.status.done": "Done",
  "workflows.status.failed": "Failed",
  "workflows.status.error": "Error",
  "workflows.status.unknown": "Unknown",

  // ── Tasks ──
  "tasks.navTitle": "Tasks",
  "tasks.title": "Tasks",
  "tasks.sessionScope": "Tasks for this session",
  "tasks.project": "Task store",
  "tasks.global": "Global",
  "tasks.loading": "Loading tasks…",
  "tasks.emptyTitle": "No tasks here",
  "tasks.emptyHint": "Tasks will appear here when the pi-tasks extension creates them.",
  "tasks.inProgress": "In progress",
  "tasks.pending": "Pending",
  "tasks.completed": "Completed",
  "tasks.untitled": "Untitled task",
  "tasks.blockedBy": "blocked by {ids}",
  "tasks.metadata": "Metadata",
  "tasks.showOutput": "Show output",
  "tasks.loadingOutput": "Loading output…",
  "tasks.store.project": "Project store",
  "tasks.store.global": "Global store",
  "tasks.store.session": "Session store",
  "tasks.storeSession": "Session {id}",
  "tasks.execution.running": "Running",
  "tasks.execution.completed": "Completed",
  "tasks.execution.failed": "Failed",
  "tasks.execution.stopping": "Stopping",
  "tasks.execution.stopped": "Stopped",
  "tasks.execution.unknown": "Unknown",

  // ── Subagents ──
  "subagents.navTitle": "Subagents",
  "subagents.title": "Subagents",
  "subagents.sessionScope": "Subagents for this session",
  "subagents.loading": "Loading subagents…",
  "subagents.emptyTitle": "No subagents yet",
  "subagents.emptyHint": "Subagents will appear here when the pi-subagents extension runs them.",
  "subagents.untitled": "Untitled subagent",
  "subagents.spawned": "Spawned {time}",
  "subagents.active": "Active {time}",
  "subagents.summary.running": "{count} running",
  "subagents.summary.done": "{count} done",
  "subagents.summary.failed": "{count} failed",
  "subagents.summary.unknown": "{count} unknown",
  "subagents.transcript": "Transcript",
  "subagents.parent": "Parent",
  "subagents.status.running": "Running",
  "subagents.status.done": "Done",
  "subagents.status.error": "Error",
  "subagents.status.unknown": "Unknown",

  // ── Command palette ──
  "palette.listSessions": "List sessions",
  "palette.closeSearch": "Close search",
  "palette.actions": "Actions",
  "palette.newSession": "New session",
  "palette.noSessionsFound": "No sessions found",
  "palette.noMatches": 'no matches for "{query}"',
  "palette.clearSearchHint": "esc clears the search",
  "palette.failedLoadSessions": "Failed to load sessions",

  // ── Session viewer ──
  "session.back": "Sessions",
  "session.toggleTree": "Toggle session tree",
  "session.new": "New",
  "session.newSession": "Start a new session",
  "session.shortcuts": "Show keyboard shortcuts",
  "session.toggleSidebar": "Toggle sidebar",
  "session.actions": "Session actions",
  "session.pinnedSessions": "Pinned sessions",
  "session.openPinnedSessions": "Switch pinned session",
  "session.loadingPinnedSessions": "Loading pinned sessions…",
  "session.noPinnedSessions": "No pinned sessions yet",
  "session.pinnedLoadFailed": "Couldn’t load pinned sessions",
  "session.pinnedUpdateFailed": "Couldn’t update this pin",
  "session.tabsAwaiting": "awaiting you",
  "session.tabsIdle": "idle",
  "session.tabsIdleAge": "idle · {age}",
  "session.pinCurrent": "Pin this session",
  "session.unpinCurrent": "Unpin this session",
  "session.archiveCurrent": "Archive this session",
  "session.restoreCurrent": "Restore this session",
  "session.archiveDisabledRunning": "Stop this session before archiving it.",
  "session.archiveDisabledWaiting": "Answer this session before archiving it.",
  "session.archiveUpdateFailed": "Couldn’t update this session’s archive state.",
  "session.loading": "Loading session…",
  "session.notFound": "Session not found",
  "session.loadFailed": "Failed to load session",
  "session.missingId": "Missing session id",
  "session.backToSessions": "Back to sessions",
  "session.runtimePageTitle": "{title} · {runtime}",
  "session.copyResumeCommand": "Copy {command} to clipboard",
  "session.resumeUnavailable": "Resume command unavailable",
  "session.viewOnly": "view only",
  "session.viewOnlyResume": "view only · resume in terminal: {command}",
  "session.workerDown": "worker down",
  "session.connectionReconnecting": "reconnecting · restoring latest session",
  "session.connectionStale": "connection stale · restoring latest session",
  "session.workerExited": "worker exited ({code}) — stream ended here",
  "session.workerExitedHint": "send your next message to restart the worker · transcript is saved",
  "session.noWorkingDirectory": "No working directory available for this session",
  "session.nativeIdTitle": "Codex thread {id}",
  "session.nativeSessionTitle": "{runtime} session {id}",
  "session.filterDefault": "Default",
  "session.filterNoTools": "No-tools",
  "session.filterUser": "User",
  "session.filterLabeled": "Labeled",
  "session.filterAll": "All",
  "session.filterDefaultTitle": "Hide settings entries",
  "session.filterNoToolsTitle": "Default minus tool results",
  "session.filterUserTitle": "Only user messages",
  "session.filterLabeledTitle": "Only labeled entries",
  "session.filterAllTitle": "Show everything",
  "session.earlierMessages": "Earlier messages",
  "session.showingLatestMessages": "Showing latest {shown} of {total} messages.",
  "session.loadEarlierCount": "Load {count} earlier",
  "session.loadingEarlier": "Loading…",
  "session.loadEarlierFailed": "Failed to load: {error}",
  "session.tasks": "Tasks",
  "session.subagents": "Subagents",
  "session.workflow": "Workflow",
  "session.pending": "pending",
  "session.inProgress": "in progress",
  "session.running": "running",
  "session.completed": "completed",

  // ── Session activity dock ──
  "session.dockAgents": "Agents",
  "session.dockTasks": "Tasks",
  "session.dockOpenAll": "open all →",
  "session.dockActive": "{count} active",
  "session.dockReady": "{count} done",
  "session.dockMoreAgents": "+{count} more",

  "session.done": "done",
  "session.failed": "failed",
  "session.error": "error",
  "session.turns": "{count} turns",
  "session.toolCalls": "{count} tool calls",
  "session.moreToolNames": "+{count} more",
  "session.showOutput": "Show output",
  "session.subagentResult": "Subagent {id} — {title}",
  "session.openDashboard": "Open dashboard",
  "session.viewAll": "View all",

  // ── Session command menu ──
  "menu.searchSessions": "Search Sessions",
  "menu.rename": "Rename",
  "menu.fork": "Fork",
  "menu.clone": "Clone",
  "menu.resumeTerminal": "Resume via Terminal",
  "menu.tree": "Tree",
  "menu.diff": "Diff",
  "menu.modelUsage": "Model Usage",
  "menu.renamePrompt": "Rename session",
  "menu.renamed": "Renamed",
  "menu.forkFailed": "Fork failed",
  "menu.noUserMessagesToFork": "No user messages to fork from",
  "menu.loadMessagesFailed": "Failed to load messages",
  "menu.cloneFailed": "Clone failed",

  // ── Diff review modal ──
  "diff.title": "Diff",
  "diff.loading": "Loading diff…",
  "diff.timeout": "Diff timed out — try again.",
  "diff.empty": "No uncommitted changes",
  "diff.notRepo": "Not a git repository",
  "diff.split": "Split",
  "diff.unified": "Unified",
  "diff.collapseAll": "Collapse all",
  "diff.expandAll": "Expand all",
  "diff.collapseFile": "Collapse file",
  "diff.expandFile": "Expand file",

  // ── Session transcript ──
  "session.you": "YOU",
  "session.assistant": "ASSISTANT",
  "session.forkFromMessage": "Fork session from this message",
  "session.copyMessage": "Copy message",
  "session.copyMessageLink": "Copy link to this message",
  "session.activitySummary": "{seconds}s thinking · {count} {runs}",
  "session.activityRun": "tool run",
  "session.activityRuns": "tool runs",
  "session.activityEdits": " · edits",
  "session.activityRunning": "running {command} · {elapsed}",
  "session.activitySeconds": "{count}s",
  "session.activityThinking": "thinking",
  "session.activityTool": "tool",
  "session.openFullDiff": "open full diff",
  "session.copyPatch": "copy patch",

  // ── Right sidebar ──
  "sidebar.artifacts": "Artifacts",
  "sidebar.howArtifactsWork": "How artifacts work",
  "sidebar.expandPanel": "Expand panel",
  "sidebar.hidePanel": "Hide panel",
  "sidebar.resize": "Resize sidebar",

  // ── Chat composer ──
  "composer.placeholder": "Continue this session…",
  "composer.send": "Send",
  "composer.sendHint": "Send this message",
  "composer.steer": "Steer",
  "composer.steerNow": "Steer now",
  "composer.steerHint": "Add this message to the response in progress",
  "composer.queue": "Queue",
  "composer.queueNext": "Queue next",
  "composer.queueHint": "Queue this message for after the current response",
  "composer.queuedNext": "queued next",
  "composer.queueBadgeCount": "{count} pending messages in queue",
  "composer.queuePausedBadge": "Queue is paused",
  "composer.submitted": "submitted",
  "composer.removeQueued": "Remove queued message",
  "composer.queueActive": "Queue",
  "composer.queuePaused": "Queue paused",
  "composer.queueQueuedCount": "queued",
  "composer.queueSteeringCount": "steering",
  "composer.pause": "Pause",
  "composer.resume": "Resume",
  "composer.queuePauseHint": "Hold queued messages until you resume",
  "composer.queueResumeHint": "Auto-send queued messages when the current run ends",
  "composer.queueAria": "Pending messages",
  "composer.steerTag": "steering",
  "composer.queueNavigate": "navigate",
  "composer.queueEdit": "edit",
  "composer.queueDelete": "delete",
  "composer.queueSendNow": "send now",
  "composer.queueExit": "exit",
  "composer.queueSavedLocally": "auto-sending",
  "composer.queueSavedLocallyHint":
    "Queued messages are saved on the server and will be sent automatically when the worker is idle — even if you close the browser",
  "composer.cancel": "Cancel",
  "composer.stop": "Stop",
  "composer.idleActions": "Message actions",
  "composer.runningActions": "Running response actions",
  "composer.idle": "idle",
  "composer.unavailable": "unavailable",
  "composer.restartWorker": "send a message to restart the worker…",
  "composer.attachPhotos": "Attach photos",
  "composer.attachmentText": "Selected text",
  "composer.viewAttachment": "View selected text",
  "composer.removeAttachment": "Remove attachment",
  "composer.expand": "Expand composer",
  "composer.searchModels": "Search models…",
  "composer.switchModel": "Switch model",
  "composer.switchEffort": "Switch effort",
  "composer.modelPlaceholder": "Model",
  "composer.disabledNotice":
    "This session can be viewed, but chat is disabled because its working directory no longer exists.",
  "composer.copyPath": "Click to copy path",
  "composer.focusShortcut": "Shift + i to focus",
  "composer.cancelRunning": "Cancel running response",
  "composer.stopRunning": "Stop the running response",
  "composer.contextDetails": "Click for details",
  "composer.pathCopied": "Path copied",

  // ── Extension UI ──
  "extensionUi.title": "Extension request",
  "extensionUi.confirm": "Confirm",
  "extensionUi.send": "Send",
  "extensionUi.timeout": "{seconds}s remaining",
  "extensionUi.failed": "Couldn’t send the response. Try again.",
  "extensionUi.notification": "Extension notification",

  // ── Settings ──
  "settings.title": "Settings",
  "settings.appearance": "Appearance",
  "settings.theme": "Theme",
  "settings.themeHint": "Applies to every browser pointed at this instance.",
  "settings.themeDark": "Dark",
  "settings.themeLight": "Light",
  "settings.themeCustom": "Custom",
  "settings.themeBuiltIn": "Built-in",
  "settings.themeCommunity": "Community",
  "settings.interfaceFont": "Interface font",
  "settings.interfaceFontHint": "Font for the app UI — menus, lists, headers.",
  "settings.contentFont": "Content font",
  "settings.contentFontHint": "Font for rendered message prose. Code uses the code font.",
  "settings.codeFont": "Code font",
  "settings.codeFontHint": "Font for code, commands, and tool output. Defaults to monospace.",
  "settings.interfaceFontSize": "Interface font size",
  "settings.interfaceFontSizeHint": "Size of the app UI text (px).",
  "settings.contentFontSize": "Content font size",
  "settings.contentFontSizeHint": "Size of rendered message text (px).",
  "settings.fontBuiltIn": "Built-in",
  "settings.fontInstalled": "Installed",
  "settings.fontDetectUnsupported":
    "This browser cannot list installed fonts. Use Custom… to type a font name.",
  "settings.fontDetectDenied":
    "Could not read installed fonts (permission denied). Use Custom… to type a font name.",
  "settings.fontActions": "Actions",
  "settings.fontMono": "Monospace",
  "settings.fontSystem": "System",
  "settings.fontSans": "Sans-serif",
  "settings.fontSerif": "Serif",
  "settings.fontDetect": "Detect installed fonts…",
  "settings.fontCustomOption": "Custom…",
  "settings.fontFamilyPlaceholder": "Font family name",

  "settings.sessionsList": "Sessions List",
  "settings.spinnerStyle": "Spinner style",
  "settings.spinnerStyleHint": "Animation shown next to running sessions.",
  "settings.spinnerRuncat": "Runcat",
  "settings.spinnerBraille": "Braille",
  "settings.spinnerPacman": "Pac-Man",
  "settings.spinnerComet": "Comet",
  "settings.defaultLayout": "Default layout",
  "settings.defaultLayoutHint": "How the sessions list is grouped on load.",
  "settings.sessionTitles": "Session Titles",
  "settings.autoTitle": "Auto-generate titles",
  "settings.autoTitleHint": "Generate one clean title from the first user message.",
  "settings.whenToTitle": "When to title",
  "settings.whenToTitleHint": "Title once, or refresh after each user turn.",
  "settings.titleOnce": "Once per session",
  "settings.titleEachTurn": "Every user turn",
  "settings.titleModel": "Title model",
  "settings.titleModelHint":
    "The built-in option is instant and free. Choose a model for cleaner titles; reasoning is disabled for this short task.",
  "settings.titleBuiltin": "Built-in heuristic (no AI)",

  "settings.sessionDisplay": "Session Display",
  "settings.sessionTabs": "Pinned session tabs",
  "settings.sessionTabsHint": "Show pinned sessions inside a session for quick switching.",
  "settings.thinkingExpanded": "Show thinking by default",
  "settings.thinkingExpandedHint":
    "When on, model reasoning is expanded as sessions load. You can still toggle it per session from the header.",
  "settings.toolsVisible": "Show tool calls by default",
  "settings.toolsVisibleHint":
    "When off, tool invocations and compactions are hidden as sessions load — handy on small screens.",
  "settings.toolOutputsExpanded": "Expand tool outputs by default",
  "settings.toolOutputsExpandedHint":
    "When on, tool output blocks load expanded instead of collapsed.",

  "settings.artifacts": "Artifacts",
  "settings.showArtifacts": "Show Artifacts panel",
  "settings.showArtifactsHint":
    "Surface files the agent wrote and sizeable code blocks in a right-sidebar tab. When off, the tab is hidden.",
  "settings.includeFilter": "Include filter",
  "settings.includeFilterHint":
    "Comma-separated globs (e.g. *.md, *.html, artifacts/**). Only matching files are shown. Leave empty to show everything; any filter also hides loose chat code snippets.",

  "settings.notifications": "Notifications",
  "settings.notifyReady": "Notify when a response is ready",
  "settings.notifyReadyHint": "Shows a notification when chat completes.",

  "settings.machines": "Machines",
  "settings.machinesHint":
    "Other pican instances reached over Tailscale. Their sessions appear read-only on the homepage with a link back to that machine — nothing is proxied through this one.",
  "settings.machineName": "Name",
  "settings.machineNamePlaceholder": "mac-mini",
  "settings.machineBaseUrl": "Base URL",
  "settings.machineBaseUrlPlaceholder": "https://mac-mini.tailnet-name.ts.net:31415",
  "settings.machineToken": "Token",
  "settings.machineTokenPlaceholder": "Leave blank to keep existing token",
  "settings.machineTokenSet": "Token set",
  "settings.machineTokenNotSet": "No token",
  "settings.machineAdd": "Add machine",
  "settings.machineRemove": "Remove",
  "settings.machineNoneYet": "No machines added yet.",
  "settings.machineNameRequired": "Name is required",
  "settings.machineUrlRequired": "Base URL is required",
  "settings.machineFailedLoad": "Failed to load machines",
  "settings.machineFailedSave": "Failed to save machine",
  "settings.machineFailedRemove": "Failed to remove machine",

  // ── Keyboard shortcuts modal ──
  "shortcuts.title": "Keyboard shortcuts",
  "shortcuts.searchPlaceholder": "Search shortcuts...",
  "shortcuts.searchAria": "Search keyboard shortcuts",
  "shortcuts.empty": "No matching shortcuts found",
  "shortcuts.catGeneral": "General",
  "shortcuts.catComposer": "Chat Composer",
  "shortcuts.catVim": "Vim Navigation",
  "shortcuts.vimNote": "When chat input is not active",
  "shortcuts.searchSessions": "Search sessions",
  "shortcuts.toggleSidebar": "Toggle sidebar (tree)",
  "shortcuts.newSession": "New session",
  "shortcuts.toggleTheme": "Toggle theme (dark/light)",
  "shortcuts.toggleHelp": "Toggle shortcuts help",
  "shortcuts.focusInput": "Focus chat input",
  "shortcuts.cycleThinking": "Cycle thinking mode",
  "shortcuts.switchModel": "Choose/switch model",
  "shortcuts.submit": "Submit message",
  "shortcuts.scrollDown": "Scroll down",
  "shortcuts.scrollUp": "Scroll up",
  "shortcuts.scrollTop": "Scroll to top",
  "shortcuts.scrollBottom": "Scroll to bottom",
  "shortcuts.noteOutsideInput": "Outside input",
  "shortcuts.noteInsideInput": "Inside input",

  // ── Git footer (branch + PR actions) ──
  "git.createPr": "Create PR",
  "git.createDraftPr": "Create Draft PR",
  "git.createPrManually": "Create PR manually",
  "git.viewPr": "View PR",
  "git.mergePr": "Merge PR",
  "git.noRemote": "No GitHub remote configured",
  "git.renameFailed": "Rename failed",
  "git.currentBranch": "Current branch",
  "git.renameBranch": "Rename branch",
  "git.newBranchName": "New branch name",
  "git.moreActions": "More git actions",

  // ── Artifacts panel actions ──
  "artifact.copy": "Copy",
  "artifact.copySource": "Copy source",
  "artifact.download": "Download",
  "artifact.preview": "Preview",
  "artifact.runPreview": "Run preview",
  "artifact.showSource": "Show source",
  "artifact.emptyHidden":
    '{count} {noun} hidden by your filter — adjust in <a href="{settingsHref}">Settings</a>.',
  "artifact.emptyNone": "No artifacts in this session yet.",
  "artifact.nounOne": "artifact",
  "artifact.nounMany": "artifacts",

  // ── Artifacts help modal (HTML — rendered via {@html}) ──
  "artifactHelp.intro":
    "<strong>Artifacts</strong> are the files the agent wrote and the larger code blocks it shared, pulled out of the conversation so you can find, read, copy, or download them in one place.",
  "artifactHelp.viewing":
    "<strong>Viewing.</strong> Pick one from the list to see its source. HTML, SVG, and Markdown files also have a <em>Preview</em> toggle — HTML/SVG run in a secure sandbox, Markdown renders as formatted text.",
  "artifactHelp.upToDate":
    "<strong>Staying up to date.</strong> Files the agent <em>writes</em> or <em>edits</em> update automatically, and simple renames or deletes (<code>mv</code>, <code>git mv</code>, <code>rm</code>) are tracked too. But changes made through other shell commands — like <code>sed</code> or output redirects — can't be followed from the conversation, so once in a while an artifact may show an older version. When in doubt, check the file on disk.",
  "artifactHelp.note":
    "Artifacts are part of the live view only and aren't included in exported snapshots.",

  // ── Version modal ──
  "version.dialogLabel": "pican version",
  "version.unavailable": "Version information is unavailable.",
  "version.checkForUpdates": "Check for updates",
  "version.checking": "Checking…",
  "version.couldNotCheck": "Could not check for updates.",
  "version.devBuild": "You're running a local development build.",
  "version.latestPublished": "Latest published: {version}",
  "version.devUpdateDisabled":
    "In-app update is disabled here so it can't overwrite local changes.",
  "version.updateAvailable": "Update available:",
  "version.releaseNotes": "release notes",
  "version.updateRestart": "Update & Restart",
  "version.later": "Later",
  "version.lastChecked": "Last checked {when}.",
  "version.onLatest": "You're on the latest version.",
  "version.noReleaseNotes": "No release notes.",
  "version.installing": "Installing update…",
  "version.restarting": "Restarting server…",
  "version.updateFailed": "Update failed: {error}",
  "version.reconnecting": "Reconnecting…",
  "version.serverNotBack": "Server did not come back. Reload the page manually.",

  // ── Not found (404) ──
  "notFound.heading": "This page wandered off",
  "notFound.message": "Even the cat couldn't sniff it out. Let's get you home.",
  "notFound.back": "Back to sessions",
  "notFound.catAlt": "A puzzled cat",
};
